apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.iperf.server.deployment.name}}
  labels:
    app: {{.Values.iperf.server.labels.app}}
    belongsToApp: {{.Values.iperf.server.labels.belongsToApp}}
spec:
  replicas: {{.Values.iperf.server.replicas}}
  selector:
    matchLabels:
      app: {{.Values.iperf.server.labels.app}}
  template:
    metadata:
      labels:
        app: {{.Values.iperf.server.labels.app}}
    spec:
      containers:
      - name: {{.Values.iperf.server.container.name}}
        image: {{.Values.iperf.image}}
        command: ["iperf"]
        args: ["-s", "-p", "{{.Values.iperf.server.port}}"]
        ports:
        - containerPort: {{.Values.iperf.server.port}}
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
---
kind: Service
apiVersion: v1
metadata:
  name: {{.Values.iperf.server.service.name}}
  labels:
    belongsToApp: {{.Values.iperf.server.labels.belongsToApp}}
spec:
  selector:
    app: {{.Values.iperf.server.labels.app}}
  ports:
  - protocol: TCP
    port: {{.Values.iperf.server.port}}
    targetPort: {{.Values.iperf.server.targetPort}}
