apiVersion: apps/v1
kind: Deployment
metadata:
  name: iperf-server-deployment
  labels:
    app: iperf-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: iperf-server
  template:
    metadata:
      labels:
        app: iperf-server
    spec:
      containers:
      - name: iperf-server
        image: amitpandia/iperf:v1.0
        command: ["iperf"]
        args: ["-s", "-p", "5010"]
        ports:
        - containerPort: 5010

