apiVersion: v1
kind: Secret
metadata:
  name: {{.Values.TELEMETRY_AGENT_SECRET}}
  namespace: default
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJwbGF0aW5hbmV4dXMuYXVjdGFjb2duaXRpby5jb206ODA4MyI6IHsKCQkJImF1dGgiOiAiWkdWMlpXeHZjR1Z5T25Cc1lYUnBibUVoWkdWMiIKCQl9Cgl9LAoJIkh0dHBIZWFkZXJzIjogewoJCSJVc2VyLUFnZW50IjogIkRvY2tlci1DbGllbnQvMTkuMDMuMCAobGludXgpIgoJfQp9
type: kubernetes.io/dockerconfigjson
