apiVersion: v1
kind: Service
metadata:
  name: {{.Values.MYSQL_APP_NAME}}
  labels:
    app: {{.Values.APP_NAME}}
spec:
  ports:
    - port: {{.Values.MYSQL_PORT}}
  selector:
    app: {{.Values.APP_NAME}}
    tier: mysql
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{.Values.MYSQL_PV_NAME}}
  labels:
    app: {{.Values.APP_NAME}}
spec:
  storageClassName: {{.Values.STORAGE_CLASS_NAME}}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{.Values.MYSQL_STORAGE}}
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: {{.Values.MYSQL_APP_NAME}}
  labels:
    app: {{.Values.APP_NAME}}
spec:
  storageClassName: {{.Values.STORAGE_CLASS_NAME}}
  selector:
    matchLabels:
      app: {{.Values.APP_NAME}}
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{.Values.APP_NAME}}
        tier: mysql
    spec:
      containers:
      - image: {{.Values.MYSQL_IMAGE}}
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        ports:
        - containerPort: {{.Values.MYSQL_PORT}}
          name: mysql
        volumeMounts:
        - name: {{.Values.MYSQL_VOLUME_MOUNT}}
          mountPath: /var/lib/mysql
      volumes:
      - name: {{.Values.MYSQL_VOLUME_MOUNT}}
        persistentVolumeClaim:
          claimName: {{.Values.MYSQL_PV_NAME}}

