apiVersion: apps/v1
kind: Deployment
metadata:
  name: iperf-svc-to-ext-server-deployment-app
  labels:
    app: iperf-server-ext-app
    belongsToApp: iperf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iperf-server-ext-app
  template:
    metadata:
      labels:
        app: iperf-server-ext-app
    spec:
      containers:
      - name: iperf-server-ext-app
        image: amitpandia/iperf:v1.0
        command: ["iperf"]
        args: ["-s", "-p", "5040"]
        ports:
        - containerPort: 5040
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
